package com.desropolis.st.model.admin;

import static org.junit.Assert.*;

import java.util.Date;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.google.appengine.tools.development.testing.LocalServiceTestHelper;
import com.googlecode.objectify.Key;
import com.googlecode.objectify.Objectify;
import com.googlecode.objectify.ObjectifyFactory;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration({"/test-context.xml"})
public class JobTest {

	@Autowired
	private LocalServiceTestHelper helper;

	@Autowired
	private ObjectifyFactory objectifyFactory;

	@Before
	public void setUp() {
		helper.setUp();
	}

	@After
	public void tearDown() {
		helper.tearDown();
	}

	// run this test twice to prove we're not leaking any state across tests
	private void doTest() {
		
		Objectify ofy = objectifyFactory.begin();
		
		Job job = new Job("TE-001");
		ofy.put(job);
		assertNotNull(job.id);    // id was autogenerated

		Job fetched1 = ofy.get(new Key<Job>(Job.class, job.id));
		Job fetched2 = ofy.get(Job.class, job.id);    // equivalent, more convenient
		assertEquals(job, fetched1);
		assertEquals(fetched1, fetched2);
		
		job.startDate = new Date();
		ofy.put(job);
		
		ofy.delete(job);

	}

	@Test
	public void testInsert1() {
		doTest();
	}

	@Test
	public void testInsert2() {
		doTest();
	}

}
